// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "displayname", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebauthnCredentialsColumns holds the columns for the "webauthn_credentials" table.
	WebauthnCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "credential", Type: field.TypeJSON},
		{Name: "user_credentials", Type: field.TypeString},
	}
	// WebauthnCredentialsTable holds the schema information for the "webauthn_credentials" table.
	WebauthnCredentialsTable = &schema.Table{
		Name:       "webauthn_credentials",
		Columns:    WebauthnCredentialsColumns,
		PrimaryKey: []*schema.Column{WebauthnCredentialsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "webauthn_credentials_users_credentials",
				Columns:    []*schema.Column{WebauthnCredentialsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		WebauthnCredentialsTable,
	}
)

func init() {
	WebauthnCredentialsTable.ForeignKeys[0].RefTable = UsersTable
}
