// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hesusruiz/faster/ent/schema"
	"github.com/hesusruiz/faster/ent/user"
	"github.com/hesusruiz/faster/ent/webauthncredential"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	webauthncredentialMixin := schema.WebauthnCredential{}.Mixin()
	webauthncredentialMixinFields0 := webauthncredentialMixin[0].Fields()
	_ = webauthncredentialMixinFields0
	webauthncredentialFields := schema.WebauthnCredential{}.Fields()
	_ = webauthncredentialFields
	// webauthncredentialDescCreateTime is the schema descriptor for create_time field.
	webauthncredentialDescCreateTime := webauthncredentialMixinFields0[0].Descriptor()
	// webauthncredential.DefaultCreateTime holds the default value on creation for the create_time field.
	webauthncredential.DefaultCreateTime = webauthncredentialDescCreateTime.Default.(func() time.Time)
	// webauthncredentialDescUpdateTime is the schema descriptor for update_time field.
	webauthncredentialDescUpdateTime := webauthncredentialMixinFields0[1].Descriptor()
	// webauthncredential.DefaultUpdateTime holds the default value on creation for the update_time field.
	webauthncredential.DefaultUpdateTime = webauthncredentialDescUpdateTime.Default.(func() time.Time)
	// webauthncredential.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	webauthncredential.UpdateDefaultUpdateTime = webauthncredentialDescUpdateTime.UpdateDefault.(func() time.Time)
	// webauthncredentialDescID is the schema descriptor for id field.
	webauthncredentialDescID := webauthncredentialFields[0].Descriptor()
	// webauthncredential.IDValidator is a validator for the "id" field. It is called by the builders before save.
	webauthncredential.IDValidator = webauthncredentialDescID.Validators[0].(func(string) error)
}
