// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hesusruiz/faster/ent/predicate"
	"github.com/hesusruiz/faster/ent/webauthncredential"
)

// WebauthnCredentialDelete is the builder for deleting a WebauthnCredential entity.
type WebauthnCredentialDelete struct {
	config
	hooks    []Hook
	mutation *WebauthnCredentialMutation
}

// Where appends a list predicates to the WebauthnCredentialDelete builder.
func (wcd *WebauthnCredentialDelete) Where(ps ...predicate.WebauthnCredential) *WebauthnCredentialDelete {
	wcd.mutation.Where(ps...)
	return wcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wcd *WebauthnCredentialDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wcd.hooks) == 0 {
		affected, err = wcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WebauthnCredentialMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wcd.mutation = mutation
			affected, err = wcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wcd.hooks) - 1; i >= 0; i-- {
			if wcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcd *WebauthnCredentialDelete) ExecX(ctx context.Context) int {
	n, err := wcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wcd *WebauthnCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: webauthncredential.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: webauthncredential.FieldID,
			},
		},
	}
	if ps := wcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// WebauthnCredentialDeleteOne is the builder for deleting a single WebauthnCredential entity.
type WebauthnCredentialDeleteOne struct {
	wcd *WebauthnCredentialDelete
}

// Exec executes the deletion query.
func (wcdo *WebauthnCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := wcdo.wcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{webauthncredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wcdo *WebauthnCredentialDeleteOne) ExecX(ctx context.Context) {
	wcdo.wcd.ExecX(ctx)
}
