server:
  listenAddress: ":3000"
  staticDir: "docs"
  templateDir: "back/templates"

store:
  driverName: "sqlite3"
  dataSourceName: "file:webauthn.sqlite?mode=rwc&cache=shared&_fk=1"

webauthn:
  RPDisplayName: "Gaia-X AISBL"
  RPID: "localhost"
  RPOrigin: "http://localhost:8000"
  AuthenticatorAttachment: "cross-platform"
  UserVerification: "required"

