// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WebauthnCredential is the predicate function for webauthncredential builders.
type WebauthnCredential func(*sql.Selector)
